### ISSUE TITLE
Frapi on Shared Webhost

### ISSUE THREAD

**Issue by Max13** [frapi/frapi#95]
Hi,

I know: "Frapi is not made for shared hosting".

I'm using it on shared webhosting, not because I don't know how to configure correctely apache (which can be possible) but because I'm the founder of a french non-profit organization, which aims at providing free and low cost web hosting.
Instead of spending money, I wanted to use our servers.

So, here are some problems, and I know (hope) you have a solution:
- Frapi needs some cache mechanism, like apc. Our php is executed as DSO, so APC wasn't available. We switched our conf to php_cgi, and then we've installed apc. This part is ok.
- Then the HTTP_Digest_auth became broken, and I've read that it's because some headers in cgi are not sent correctely to apache...

So, what can I do, CGI, no HTTP_Auth, or DSO and no APC? (I know that there are other cache)
Any idea would be great :)
Thanks for this amazing tool !

**Comment by helgi** [comment]
For the APC problem, you can use a cache called "dummy" which basically means there is no cache but you also lose the performance gains a cache provides. You could also use memcache(d) as it only requires you to have the extension around and the actual memcache server can be hosted elsewhere.

The Digest problem, are you using the latest version of FRAPI from github? There were a few digest fixes merged in the past few days.

**Comment by Max13** [comment]
Hi,
There are some changes, improvements, but the HTTP_Auth is still broken with php as CGI.

I don't think there is anything to do from frapi, I think HTTP headers are not sent correctely to apache by php as cgi, that's it.
But, maybe frapi could change its auth method, or give the dev, a choice between 2 or more methods ?

**Comment by dshafik** [comment]
@Max13 we have successfully deployed Digest auth with both Apache+mod_php and nginx+php-fpm; could you give me a little more info on your setup so we can recreate it and see if there is a code issue?

As for authentication methods, changes by @clayhinson in #123 allow you to specify a custom auth mechanism, by assigning an object instance of class extended from `Frapi_Authorization` to `$customAuthorization` in the global scope of your `AllFiles.php` file.

**Comment by Max13** [comment]
@dshafik Here is my [phpinfo()](http://dev.rihan.fr/phpinfo.php), there my [apache backend vhost](http://pastebin.com/VRERET8c) by CPanel, and finally my [nginx frontend vhost](http://pastebin.com/Vym9F8GH)

The domain on these files is "dev.rihan.fr", but frapi isn't installed there. I've installed frapi on a default vhost, which is the same as above files.

Tell me if you need a webhosting to test it yourself.

**Comment by dshafik** [comment]
@Max13 so you are using nginx as a frontend -> apache -> fastcgi ? Is there a reason not to skip Apache? I'm pretty sure this is a system issue.

**Comment by Max13** [comment]
@dshafik Actually, when I wrote my issue, I didn't have nginx. It was Apache (same vhost but on :80) -> fastcgi.
I've installed NGinx as frontend 2 months ago.
